language: python

python:
  - "pypy3.5"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -p '*_test.py'
